json_feeds:
  - title: Galaxy News
    url: https://galaxyproject.org/news/feed.json
    list_key: "news"
    format: "{tease}\n{link}\n{images}"

    # Medias should get grouped if they need to be in same file or seperated
    # This is needed while in bluesky the characters are limited and we need
    # it to be seperated from the the main file to edit it seperately
    media:
      global:
        group1:
          - linkedin-galaxyproject
        group2:
          - bluesky-galaxyproject
      eu:
        - matrix-eu-announce
        - mastodon-eu-freiburg
      us:
        - mastodon-galaxyproject

    mentions:
      all:
        mastodon-eu-freiburg:
          - galaxyproject@mstdn.science
        mastodon-galaxyproject:
          - galaxyfreiburg@bawÃ¼.social

    hashtags:
      all:
        mastodon-eu-freiburg:
          - UseGalaxy
          - GalaxyProject
          - EOSC
        mastodon-galaxyproject:
          - UseGalaxy
          - GalaxyProject
        bluesky-galaxyproject:
          - UseGalaxy
          - GalaxyProject
        linkedin-galaxyproject:
          - UseGalaxy
          - GalaxyProject
      esg:
        mastodon-eu-freiburg:
          - EuroScienceGateway
        mastodon-galaxyproject:
          - EuroScienceGateway
        bluesky-galaxyproject:
          - EuroScienceGateway
        linkedin-galaxyproject:
          - EuroScienceGateway
      eu:
        bluesky-galaxyproject:
          - EOSC
        mastodon-galaxyproject:
          - EOSC
        linkedin-galaxyproject:
          - EOSC
      freiburg:
        mastodon-eu-freiburg:
          - UniFreiburg

  - title: "Galaxy Events"
    url: https://galaxyproject.org/events/feed.json
    list_key: "events"
    format: "ðŸ“£ {title}\n\n{tease}\n\nðŸ“… {date}\nðŸ”— More info & registration: {link}\n\n{images}"

    media:
      global:
        group1:
          - linkedin-galaxyproject
        group2:
          - bluesky-galaxyproject
      eu:
        - mastodon-eu-freiburg
        - matrix-eu-announce
      us:
        - mastodon-galaxyproject

    mentions:
      all:
        mastodon-eu-freiburg:
          - galaxyproject@mstdn.science
        mastodon-galaxyproject:
          - galaxyfreiburg@bawÃ¼.social

    hashtags:
      all:
        mastodon-eu-freiburg:
          - UseGalaxy
          - GalaxyProject
          - EOSC
          - EuroScienceGateway
        mastodon-galaxyproject:
          - UseGalaxy
          - GalaxyProject
        bluesky-galaxyproject:
          - UseGalaxy
          - GalaxyProject
        linkedin-galaxyproject:
          - UseGalaxy
          - GalaxyProject
      eu:
        bluesky-galaxyproject:
          - EOSC
          - EuroScienceGateway
        mastodon-galaxyproject:
          - EOSC
          - EuroScienceGateway
        linkedin-galaxyproject:
          - EOSC
          - EuroScienceGateway
      freiburg:
        mastodon-eu-freiburg:
          - UniFreiburg

# youtube_channels:
#   - channel: "https://www.youtube.com/c/galaxyproject"
#     format: "ðŸŽ¥ New YouTube Video Released!\n\n{title}\n\nðŸ”— Watch it now: {link}"


# citations:
#   - zotero_group_id: 1732893
#     tag: ">UseGalaxy.eu || >RNA Workbench || RNA workbench || >ASaiM || >Live EU || >Proteomics EU || >Metagenomics EU || >ML Workbench || >ChemicalToolbox"
#     format: "ðŸ“° New publication Released!\n\n{title}\nBy: {creators}\n{url}"
