feeds:
  - url: https://galaxyproject.org/eu/feed.atom

    format: "ðŸ“ New blog post Released!\n{summary}\n{link}\n{images}"

    # Medias should get grouped if they need to be in same file or seperated
    # This is needed while in bluesky the characters are limited and we need
    # it to be seperated from the the main file to edit it seperately
    media:
      - group1:
        - mastodon-eu-freiburg
        - matrix-eu-announce
        - linkedin-galaxyproject
      - group2:
        - bluesky-galaxyproject

    mentions:
      mastodon-eu-freiburg:
        - galaxyproject@mstdn.science
      bluesky-galaxyproject:
        - galaxyproject.bsky.social

    hashtags:
      mastodon-eu-freiburg:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway
      bluesky-galaxyproject:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway
      linkedin-galaxyproject:
        - UseGalaxy
        - GalaxyProject
        - UniFreiburg
        - EOSC
        - EuroScienceGateway

# youtube_channels:
#   - channel: "https://www.youtube.com/c/galaxyproject"
#     format: "ðŸŽ¥ New YouTube Video Released!\n\n{title}\n\nðŸ”— Watch it now: {link}"


# citations:
#   - zotero_group_id: 1732893
#     tag: ">UseGalaxy.eu || >RNA Workbench || RNA workbench || >ASaiM || >Live EU || >Proteomics EU || >Metagenomics EU || >ML Workbench || >ChemicalToolbox"
#     format: "ðŸ“° New publication Released!\n\n{title}\nBy: {creators}\n{url}"
